POST http://localhost:3001/api/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlcnJpIiwiaWQiOiI2NmE4ZTdkOTM4ZjIwNzM0MWZjYzZmZGQiLCJpYXQiOjE3MjIzNDU0MzN9.8-8xIJFlNggtD8ltQBIpi-vHkoq3-2V_z5owdQd2Vgg

{
    "title": "task1",
    "note": "asap",
    "time": 120
}