POST http://localhost:3001/api/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InphZ2FuIiwiaWQiOiI2NmEwZWJjYmYzOTdiNWU3MmZkOTQyMDEiLCJpYXQiOjE3MjE4MjIxNTV9.idLxy9K2ifJRqkd2WyDX-1GqRA6cm7iT8JFSpNyIOMo

{
    "title": "task1",
    "note": "asap",
    "time": 120
}