DELETE http://localhost:3001/api/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pdSIsImlkIjoiNjZhYjU3MjU4MjY2NTAzOGZkMTljMzQ1IiwiaWF0IjoxNzIyNTA0OTk3fQ.UcC4DjDcZnsbT03JmfpTMiIb07RDNO4q82D04rOC0k4

{
    "remove": "66ab573782665038fd19c348",
    "done": false
}